:Author: sjersjb
:Email: {AuthorEmail}
:Date: 30/01/2023
:Revision: version 1
:License: Public Domain

= Project: {Project}

This is a testfile for monitoring the voltage monitoring of the main battery in a battery elimination circuit.

== Step 1: Installation
The steps to install this project.

1. Open this file
2. Edit as you like (has been built with Arduino Nano)
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram BatteryMonitor.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== TO DO
* check whether vpow changes based on load (example when being loaded by grove relay)
* Identify battery connected based on the voltage measurement. 
* In the case of no battery connected, voltage is zero, minimum limit is set
* In the case of a voltage measurement, type of battery is identified NIMH, Lipo 3S or lipo 5s?
* Different states to be added corresponding to the batteries

=== Folder structure

....
 Voltage_monitor                => Arduino sketch folder
  ├── Voltage_monitor.ino       => main Arduino file
  ├── BatteryMonitor.png        => image of the the layout
  ├── layout.png                => (optional) an image of the layout
  └── ReadMe.adoc               => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact sjersjb https://id.arduino.cc/sjersjb

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| AA | Arduino Nano   | -           | 1
| R1 | 100k Resistor  | -           | 1
| R2 | 39k Resistor   | -           | 2
| A5 | pin A5 Arduino | -           | 1
| K1 | Grove relay    | -           | 1
| D5 | pin d5 Arduino | -           | 1
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
